title: Christian Baumann
subtitle: Programmer
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://chbauman.github.io/" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
    - text: About
      url: /about
    - text: Contact Me
      url : /contact
    
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
        thumbnail: default_post.png

# Edit these details 

author_logo: profile.png
author: Christian Baumann
author_bio: Hi, My Name is Chris. V5
author_email: "chbauman@student.ethz.ch"
author_location: Switzerland
author_website_url: "https://chbauman.github.io/"

author_work_experiences: 
            - company_name: AGFA Gevaert
              company_logo: agfa.png
              company_url: https://www.agfa.com/
              designation: Research Intern
              description: Worked on image processing using machine learning.
              visibility: true

author_education_details:
              - college_logo: eth.png
                college_name: ETH Zürich
                college_url: https://ethz.ch/
                college_degree: Computational Science and Engineering (On-Going)
                description: Master of Science
                visibility: true
              - college_logo: eth.png
                college_name: ETH Zürich
                college_url: https://ethz.ch/
                college_degree: Computational Science and Engineering
                description: Bachelor of Science
                visibility: true

author_project_details:
              - project_thumbnail: programmingebooks.png
                project_title: Programming Ebooks
                project_description: A Platform to easily find and read programming books
                project_url: https://programmingebooks.com
                visibility: true

# social links
github_username: chbauman
facebook_username: chrigi5.9
instagram_username: festival_chrigi

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
